@startuml

клиент --> cpa_сеть: редирект из РС
cpa_сеть --> вебмастер: оплата CPA
антифрод -- cpa_сеть: включает
трафик ..> cpa_сеть: зависит

рекламодатель --> оффер: размещает
рекламодатель --> клиент: продает товар из оффера
оффер o-- прокладка: может содержать
вебмастер --> рекламная_сеть: размещает рекламу
оффер --* cpa_сеть: размещает
оффер *-- лендинг: содержит url товара
лендинг --> оффер: трафик хост
вебмастер --> лендинг: делает
клиент --> лендинг: редирект из РС
оффер --> лид: из
лид --> заказ: конверсия в
заказ --> cpa_сеть: постбек
яндекс_direct --|> рекламная_сеть: расширяет
источник_трафика o-- рекламная_сеть: входит
тизерные_сети-тодо
@enduml