' Типы связей в РСУБД https://metanit.com/sql/tutorial/1.3.php
' 1 - * один ко многим
' 1 - 1 один к одному
' * - * многие ко многим

@startuml (id=er.ref)
note right
Справочник. Поля: 
- ИД:GUID
- Название:С(50)
end note
@enduml

@startuml (id=er.legend)
note as legend
Легенда:

Условные обозначение таблиц:
C - таблица с данными
E - таблица справочник

Типы данных сокращения:
С{размерность} - строка
ЦЧ - Целое число
ДЧ{масштаб} - Десятичное число
ДВ - ДатаВремя
Л - Битовое
Б - Бинарное
ИД - PK Key, идентификатор записи
end note
@enduml

@startuml (id=mb.onboarding)
' hide fields
!include er.puml!er.legend
' модель БД службы доставки цветов
' 
' UC
' Клиент Формирует Заказ из Букетов
' 	Клиент Выбирает Букет:Готовый
' 		Клиент Формирует Букет:Под заказ в Дизайнере Букетов
' Клиент Указывает Способ получения Заказа 
' 	Клиент Указывает Параметры (Адрес, Дата Время) Доставки Заказа
' Клиент Оплачивает Заказ через ПП
' ПП Сообщает Статус оплаты Заказа
' Флорист Собирает Заказ
' Флорист Передает Заказ Курьеру
' Курьер Доставляет Заказ
' Клиент Подтверждает получение Заказа
' Клиент Отказывается получать Заказ
' Админ Заполняет список Букеты:Готовые 

' Система Начисляет Бонусы Постоянному Клиенту за Заказ


class Клиент <<Client>> {
	*ИД ИД
	+ИДАдрес ИД
	ФИО С250
	Телефон С25
}
class Адрес <<Adress>> {
	*ИД ИД
	ИДФИАС ИД
	Адрес С500
}
Клиент "1" -- "*" Адрес

class Букет <<Flavor>> {
	*ИД ИД
	+ИДБукетТип ИД
	+ИДБукетСтатус ИД
	Название С50
}
enum БукетСтатус <<FlavorStatus>> {
	Создан
	В наличии
	Не продается
}
!include_many er.puml!er.ref
Букет "1" -- "*" БукетСтатус
enum БукетТип <<FlavorType>> { 
	Готовый 
	ПодЗаказ 
}
Букет "1" --- "*" БукетТип

class БукетЭлемент <<FlavorItem>> {
	*ИД ИД
	+ИДТипЭлемента ИД
	Название С50
	Цена ДЧ2
}
enum ТипЭлемента <<FlavorItemType>> {
	Ленты
	Цветы
	Пленка
	Зелень
}
' !include_many er.puml!er.ref

БукетЭлемент "1" -- "*" ТипЭлемента
class СоставБукета <<CompFlavor>> {
	*ИДБукет ИД
	*ИДБукетЭлемент ИД
	Количество ЦЧ
	Цена ДЧ2
}
СоставБукета "*" -- "*" Букет 
СоставБукета "*" -- "*" БукетЭлемент

class Заказ <<Order>> {
	*ИД ИД
	+ИДКлиент ИД
	+ИДЗаказСтатус ИД
	+ИДЗаказСпособПолучения ИД
	Номер С20
	ДатаВремя ДВ
	Цена ДЧ2
}
Клиент "1" - "*" Заказ 
enum ЗаказСтатус <<OrderStatus>> {
	Создан
	Оплачен
	НеОплачен
	Сборка
	Доставка
	Получен
	Отказ
	Отменен
} 
Заказ "1" -- "*" ЗаказСтатус
enum ЗаказСпособПолучения <<DeliveryType>> {
	Самовывоз
	Доставка
}
Заказ "1" -- "*" ЗаказСпособПолучения
class СоставЗаказа <<CompOrder>> {
	*ИДБукет ИД
	*ИДЗаказ ИД
}
СоставЗаказа "*" -- "*" Букет
СоставЗаказа "*" -- "*" Заказ

class Платеж <<Payment>> {
	*ИД ИД
	+ИДЗаказ ИД 
	+ИДСтатусПлатежа ИД
	+ИДПлатежаExt ИД
	ДатаВремя ДВ
	Сумма ДЧ2
	ОтКого С50
}
Заказ "1" -- "1" Платеж
enum СтатусПлатежа {
	Инициирован
	Оплачен
	ОтмененПоСроку
}
Платеж "1" -- "*" СтатусПлатежа

class Доставка <<Delivery>> {
	*ИД ИД
	+ИДДоставкаСтатус ИД
	+ИДАдрес ИД
	ДатаВремяСоздания ДВ
	ДатаВремяПолучения ДВ
}
Доставка "1" --- "*" Адрес
enum ДоставкаСтатус <<DeliveryStatus>> {
	Создана
	Доставляется
	Получен
	Отменена
}
Доставка "1" -- "*" ДоставкаСтатус

class Офис <<Office>> {
	*ИД ИД
	+ИДАдрес ИД
	Название С50
	РежимРаботы С50
}
Офис "1" - "*" Адрес

@enduml