@startuml object

' Ассоциация - это такой тип при котором объекты будут ссылаться друг на друга. При этом они остаются полностью независимыми друг от друга.
' Агрегация - это тип отношений когда один объект является частью другого. Агрегация образует слабую связь между объектами. Все зависимые классы инициализируются вне основного объекта. Комната-мебель
' Композиция - это тип отношений при котором один объект может принадлежать только другому объекту и никому другому. При композиции образуется сильная связь между объектами. При таком типе отношений основной объект полностью обеспечивает жизненный цикл объектов от которых он зависит. Комната-стена

car "1" *-- "many" wheel : contains, composition, owns
garage o-- car : include, aggregation, has
garage o-- tools: aggregation
car ..> fuel: uses, dependency
car --> road: order, direct association
car <|-- audi: Extension, inheritance
driver - car : association, drives >
@enduml