@startuml DDD

title Domain Driven Development

class Смысловое_Ядро <<Core Domain>>
class Предметная_Область <<Domain>>
class Предметная_Подобласть <<Subdomain>>
Предметная_Область "1" -- "*" Предметная_Подобласть: включает 
Смысловое_Ядро -- Предметная_Область: важна бизнесу
class Ограниченный_контекст <<Bounded Context>>
Ограниченный_контекст -- Предметная_Область : единый язык
class Карта_контекстов <<Map Context>>
Карта_контекстов - Ограниченный_контекст: содержит


class Агрегат
'class Объект
class Прикладной_сервис <<Application service>>
class Служба <<Service>>
Служба - Агрегат
class Фабрика
class Модуль <<Namespace>>
class Событие <<Domain event>>
Агрегат -- Событие : создает
class Хранилище_событий
Событие -- Хранилище_событий: хранится
class Хранилище <<Repository>>
Агрегат -- Хранилище: хранится
class Объект_значение <<Value object>>
Агрегат "1" -- "*" Объект_значение: содержит
class Сущность
Агрегат "1" -- "*" Сущность: ссылка

class Метод
Сущность -- Метод

@enduml