@startmindmap (id=IC)

* Ingress Controller
** Service Discovery
** Web Socket
** Auth
** Namespace
** Load Balance
*** Round Robin
*** RDP Cookie
** DDOS защита
*** Rate Limit

left side

** Сбои
*** Health Check
*** Circuit Breaker
*** Bulkhead
** Трассировка запросов
** SSL
** Роутинг трафика
** Правила маршрутизации
*** Canary
*** A\B
*** Green
** Варианты
*** Istio Envoy
*** Nginx Lua
*** HAProxy
*** Kong

@enduml

