@startmindmap (id=IC)

' class jenkins

' jenkins --> pipeline : содержит
' jenkins --> job : выполняет
' pipeline "1" --> "*" stage : включает
' pipeline --> jenkins_file : описывает

* Ingress Controller
** Service Discovery
** Web Socket
** Auth
** Namespace
** Load Balance
*** Round Robin
*** RDP Cookie
** DDOS защита
*** Rate Limit

left side

** Сбои
*** Health Check
*** Circuit Breaker
*** Bulkhead
** Трассировка запросов
** SSL
** Роутинг трафика
** Правила маршрутизации
*** Canary
*** A\B
*** Green
** Варианты
*** Istio Envoy
*** Nginx Lua
*** HAProxy
*** Kong

@enduml

@startmindmap (id=k8s)
* k8s
** Deployment CICD
** Volume
*** Size
*** Access Type
*** Storage Class
** YAML описание
** ReplicaSet \n масштабирование гориз-е
** Pod
*** один IP, одна подсеть
*** Контейнер
*** Label
** Load Balancer

left side
' right side

** Service
*** Pods
*** DNS
** Cluster
*** Node
**** Worker
**** Master
** Job
*** CronJob
*** Migrations Pod
** Namespace Tags

@endmindmap
