@startmindmap (id=arch)

* Архитектура 
	* Функционал Бизнес цели
	* Масштабирование
	* Атрибуты качества
	* Тех долг Roadmap
	* Безопасность

!include arch.puml!ability		
@endmindmap

@startmindmap (id=ability)

* Атрибуты качества
	* Надежность
		* Доступность Availability
		* Отказоустойчивость Fault Tolerance
		* Стабильность Resilience
		* Изоляция сбоев
	* Производительность Permormance \n Быстродействие
	* Безопасность
	* Гибкость к изменениям будущим
	* Поддерживаемость
		* Наблюдаемость Observability


@endmindmap