server {
  listen       80;
  server_name test-cnets.iqi.internal;
  proxy_set_header IsAdmin $isadmin;

  access_log  /var/log/nginx/test-cnets.iqi.internal-access.log post;
  error_log /var/log/nginx/test-cnets.iqi.internal-error.log;

  location ~ ^/admin/realms/ {
      proxy_http_version 1.1;
      proxy_pass http://test-cnets.iqi.internal-logger;
    }

  set $isadmin false;
    if ($request_uri ~ ^/admin) {
      set $isadmin true;
    }

  location ~ ^/admin/ {
    if ($remote_addr !~ "^(172\.16\.167\.14|172\.16\.167\.15|172\.16\.167\.16|172\.16\.167\.21|172\.31\.1\.133|172\.31\.1\.222|172\.31\.1\.131|172\.30\.11\.53|172\.16\.253\.40|172\.31\.1\.87|172\.16\.253\.26)$") {
      return 403;
    }

    rewrite ^/admin/(.*)$ /$1;
  }

}