@startuml (@id=code)

title Паттерны распила монолита: Код

class "Измнение монолита возможно"
class "ФБ вышестоящий \n без зависимостей"
"Измнение монолита возможно" -- "ФБ вышестоящий \n без зависимостей"
	class "Паттерн Фикус-удавка"
	"ФБ вышестоящий \n без зависимостей" -- "Паттерн Фикус-удавка" 

class APIGW as "API Gateway"

class SyncAPI 
"Паттерн Фикус-удавка" -- SyncAPI 
	SyncAPI -- APIGW : Маршрутизация запросов
	SyncAPI -- APIGW : Трансформация протоколов
	class ServiceMesh as "Service Mesh" 
	SyncAPI -- ServiceMesh : Маршрутизация в Sidecar 

class AsyncAPI
"Паттерн Фикус-удавка" -- AsyncAPI 
	AsyncAPI -- "Маршрутизация на \n основе содержимого"
	AsyncAPI -- "Селективное \n потребление"

class "ФБ нижестоящий"
"Измнение монолита возможно" -- "ФБ нижестоящий"
class "Ветвление по абстракции"
"ФБ нижестоящий" -- "Ветвление по абстракции" 


class "Тестирование \n новых сервисов"
	class "Параллельное выполнение"
	"Тестирование \n новых сервисов" -- "Параллельное выполнение"
	class "Канареечный релиз" <<canary release>>
	"Тестирование \n новых сервисов" -- "Канареечный релиз"
	class "Dark (скрытые) \n или А/В-развертывания" <<dark launching>>
	"Тестирование \n новых сервисов" -- "Dark (скрытые) \n или А/В-развертывания"

"Параллельное выполнение" -- "Методы верификации"
	"Методы верификации" -- "Шпионы"

class "Измнение монолита \n НЕ возможно"
"Измнение монолита \n НЕ возможно" -- "Сотрудник декоратор"
class "Захват изменений \n в данных" <<CDC>>
"Измнение монолита \n НЕ возможно" -- "Захват изменений \n в данных"

@enduml