@startuml (@id=db)

title Паттерны распила монолита: БД


class "Совместная БД" 
"Совместная БД" -- "Статистические \n справочники"  
"Совместная БД" -- "БД as Service"  

class "Представления \n (проекции view) БД"
class "Сервис обертки \n над БД"
class "Интерфейс БД \n как служба"

class "Монолит с выставлением \n агрегата наружу"
class "Смена владельца \n данных"

"Синхронизация данных" -- "В приложении"
"Синхронизация данных" -- "Трассировочная запись"

@enduml