@startuml (@id=code)

title Паттерны распила монолита

class "Паттерн Фикус-удавка" 
class "API Gateway"
class SyncAPI 
"Паттерн Фикус-удавка" -- SyncAPI 
SyncAPI -- "API Gateway" : Маршрутизация запросов
SyncAPI -- "API Gateway" : Трансформация протоколов
class "Service Mesh" 
SyncAPI -- "Service Mesh" : Маршрутизация в Sidecar 

class AsyncAPI
"Паттерн Фикус-удавка" -- AsyncAPI 
AsyncAPI -- "Маршрутизация на основе содержимого"
AsyncAPI -- "Селективное потребление"

' <<Core Domain>>
' class Предметная_Область <<Domain>>
' class Предметная_Подобласть <<Subdomain>>
' Предметная_Область "1" -- "*" Предметная_Подобласть: включает 
' Смысловое_Ядро -- Предметная_Область: важна бизнесу
' class Ограниченный_контекст <<Bounded Context>>
' Ограниченный_контекст -- Предметная_Область : единый язык
' class Карта_контекстов <<Map Context>>
' Карта_контекстов - Ограниченный_контекст: содержит

@enduml