@startuml (@id=code)

title Паттерны распила монолита

class "Измнение монолита возможно"
class "Паттерн Фикус-удавка"
class "ФБ вышестоящий без зависимостей"
"Измнение монолита возможно" -- "ФБ вышестоящий без зависимостей"
"ФБ вышестоящий без зависимостей" -- "Паттерн Фикус-удавка" 
class "API Gateway"
class SyncAPI 
"Паттерн Фикус-удавка" -- SyncAPI 
SyncAPI -- "API Gateway" : Маршрутизация запросов
SyncAPI -- "API Gateway" : Трансформация протоколов
class "Service Mesh" 
SyncAPI -- "Service Mesh" : Маршрутизация в Sidecar 

class AsyncAPI
"Паттерн Фикус-удавка" -- AsyncAPI 
AsyncAPI -- "Маршрутизация на основе содержимого"
AsyncAPI -- "Селективное потребление"


class "ФБ нижестоящий"
"Измнение монолита возможно" -- "ФБ нижестоящий"
class "Ветвление по абстракции"
"ФБ нижестоящий" -- "Ветвление по абстракции" 


class "Тестирование новых сервисов"
class "Параллельное выполнение"
class "Канареечный релиз" <<canary release>>
class "Dark (скрытые) или А/В-развертывания" <<dark launching>>
"Тестирование новых сервисов" -- "Параллельное выполнение"
"Тестирование новых сервисов" -- "Канареечный релиз"
"Тестирование новых сервисов" -- "Dark (скрытые) или А/В-развертывания"

"Параллельное выполнение" -- "Методы верификации"
"Методы верификации" -- "Шпионы"

class "Измнение монолита НЕ возможно"
"Измнение монолита НЕ возможно" -- "Сотрудник декоратор"
class "Захват изменений в данных" <<CDC>>
"Измнение монолита НЕ возможно" -- "Захват изменений в данных"


' <<Core Domain>>
' Предметная_Область "1" -- "*" Предметная_Подобласть: включает 
' Смысловое_Ядро -- Предметная_Область: важна бизнесу
' class Ограниченный_контекст <<Bounded Context>>
' Ограниченный_контекст -- Предметная_Область : единый язык
' class Карта_контекстов <<Map Context>>
' Карта_контекстов - Ограниченный_контекст: содержит

@enduml